version: '3.5'

services: 
  app:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:$TAG_DEPLOY
    build:
      dockerfile: docker/Dockerfile
      target: production-stage
      context: .
    container_name: progression_app_$CI_ENVIRONMENT_SLUG
    ports:
      - 127.0.0.1:$INSTANCE_PORT:8080
    env_file:
      - ${ENV_FILE:-.env}
      - VERSION

  mongo:
    image: mongo
    container_name: progression_ltijs-mongo_$CI_ENVIRONMENT_SLUG
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongo/
    ports:
      - 8081:8081    

  ltijs:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:lti_latest
    container_name: progression_ltijs_$CI_ENVIRONMENT_SLUG
    restart: always
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - mongo
        
  tests_app: 
    image: $CI_REGISTRY/$CI_PROJECT_PATH:$BRANCHE
    command: npm run test:run

  linter:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:$BRANCHE
    command: npx eslint -c eslintrc.js src/**/*.{js,vue}        
